# Greet Service Configuration
spring.application.name=greet-service

# Port on which Greet service runs
server.port=8082

# Eureka Server URL where this service will register itself
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
