# Account Microservice Configuration
spring.application.name=account-service

# Port on which Account service runs
server.port=8080

# Eureka Server URL where this service will register itself
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
