# Logging
logging.level.org.springframework=info
logging.level.com.cognizant=debug

# Hibernate SQL Logs
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.type.descriptor.sql=trace

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/ormlearn_handson5
spring.datasource.username=root
spring.datasource.password=Kumar@2006
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true