spring.application.name=spring-learn
server.port=8090
logging.level.com.cognizant.springlearn=DEBUG

app.jwt.secret=cognizant-secret-key-for-jwt-signing-minimum-256-bits
app.jwt.expiration-ms=1200000
